### ISSUE TITLE
Crash with simple_navigation 4.0.3

### ISSUE THREAD

**Issue by yld** [pdf/simple-navigation-bootstrap#13]
**undefined method `html_options=' for #<SimpleNavigation::Item:0x000000055acf30>**

````
NoMethodError - undefined method `html_options=' for #<SimpleNavigation::Item:0x000000055acf30>:
  simple-navigation-bootstrap (1.0.0) lib/simple_navigation/rendering/renderer/bootstrap.rb:55:in `tag_for'
  simple-navigation-bootstrap (1.0.0) lib/simple_navigation/rendering/renderer/bootstrap.rb:11:in `block in render'
  simple-navigation-bootstrap (1.0.0) lib/simple_navigation/rendering/renderer/bootstrap.rb:7:in `render'
  simple-navigation (4.0.3) lib/simple_navigation/item_container.rb:103:in `render'
  simple-navigation (4.0.3) lib/simple_navigation/helpers.rb:88:in `render_navigation'
  actionpack (4.2.1) lib/abstract_controller/helpers.rb:67:in `render_navigation'
app/views/application/_header.html.haml:14:in `_app_views_application__header_html_haml___3547199929432777363_108950520'
(...)
````

The code in _header.html.haml just calls a standard renderer:
 ````ruby
= render_navigation expand_all: true, level: 1..2, renderer: :bootstrap
````

**Comment by pdf** [comment]
It's possible they made some backwards-incompatible changes in 4.x, I'll try to find time to test this in the next week or so.

**Comment by xskif** [comment]
The same issue.

**Comment by pdf** [comment]
Until I can investigate how we're meant to do this on 4.x, I've released v1.0.1 which restricts compatibility to simple-navigation < 4.0.0.

**Comment by andrew2005** [comment]
1.0.1 seems to have an extra `end` introduced in d5bbaf85f98e0c454c6cef64f6a2d805b486da8e:

    simple-navigation-bootstrap-1.0.1/lib/simple_navigation/rendering/renderer/bootstrap.rb:71: syntax error, unexpected keyword_end, expecting end-of-input (SyntaxError)

Thanks for the great work.

**Comment by andrew2005** [comment]
Also in 1.0.1, 1246eee6f24405bd38cc3cfbb1f5ad005bd081c8 is giving me:

    undefined method `dropdown' for #<SimpleNavigation::ItemContainer:0x007fdc45f56508>

**Comment by pdf** [comment]
Sorry, that's embarrassing - I forgot that I haven't done a release in a while, there was some in-flight code uploaded by accident.  I've yanked v1.0.1 and v1.0.2 will be published shortly.

**Comment by andrew2005** [comment]
All good - it was Friday lunchtime after all. (I'm in Sydney)

Cheers.

**Comment by pdf** [comment]
I don't use this code much these days (been moving away from rails dev).  Should maybe have bumped the minor version for this release because there's a bit of new code, but v1.0.2 is up now.

**Comment by xskif** [comment]
I'm just rollback simple navigation to 4.0.3.
